import Colors from "./colors";

export interface Market {
  id: string;
  label: string;
  flag: string;
  color: string;
  chartexSlug: string;
}

export const MARKETS: Market[] = [
  { id: "us", label: "United States", flag: "🇺🇸", color: Colors.us, chartexSlug: "united-states" },
  { id: "uk", label: "United Kingdom", flag: "🇬🇧", color: Colors.uk, chartexSlug: "united-kingdom" },
  { id: "de", label: "Germany", flag: "🇩🇪", color: Colors.de, chartexSlug: "germany" },
  { id: "au", label: "Australia", flag: "🇦🇺", color: Colors.au, chartexSlug: "australia" },
];

export const MAJOR_LABELS = [
  "universal music",
  "sony music",
  "warner music",
  "warner records",
  "republic records",
  "interscope",
  "atlantic records",
  "columbia records",
  "epic records",
  "rca records",
  "capitol records",
  "def jam",
  "island records",
  "geffen records",
  "virgin records",
  "parlophone",
  "polydor",
  "motown",
  "island def jam",
  "umg",
  "smg",
  "wmg",
  "hollywood records",
  "elektra",
  "arista",
  "jive records",
  "mercury records",
  "verve records",
  "big machine",
  "cash money",
  "young money",
  "good music",
  "top dawg",
  "aftermath",
  "shady records",
  "quality control",
  "ovo sound",
  "cactus jack",
  "dreamville",
  "xo records",
  "rimas entertainment",
  "rimas",
  "opium",
  "10k projects",
  "88rising",
];

export const MAJOR_ARTISTS: string[] = [
  // Top tier
  "drake",
  "taylor swift",
  "michael jackson",
  "beyonce",
  "beyoncé",
  "the weeknd",
  "ariana grande",
  "justin bieber",
  "billie eilish",
  "ed sheeran",
  "rihanna",
  "katy perry",
  "lady gaga",
  "bruno mars",
  "post malone",
  "travis scott",
  "kendrick lamar",
  "j. cole",
  "j cole",
  "nicki minaj",
  "doja cat",
  "olivia rodrigo",
  "sza",
  "harry styles",
  "dua lipa",
  "bad bunny",
  "karol g",
  "peso pluma",
  "rosalía",
  "rosalia",
  "shakira",
  "miley cyrus",
  "selena gomez",
  "demi lovato",
  "shawn mendes",
  "camila cabello",
  "halsey",
  "lorde",
  "sam smith",
  "adele",
  "maroon 5",
  "imagine dragons",
  "coldplay",
  "onerepublic",
  "twenty one pilots",
  "fall out boy",
  "panic! at the disco",
  "panic at the disco",
  "paramore",
  "green day",
  "blink-182",
  "blink 182",
  "foo fighters",
  "red hot chili peppers",
  "metallica",
  "u2",
  "radiohead",
  "arctic monkeys",
  "tame impala",
  "gorillaz",
  "the killers",
  "kings of leon",
  "bon iver",
  "florence + the machine",
  "florence and the machine",
  "lana del rey",
  "mitski",
  "phoebe bridgers",
  "clairo",
  "steve lacy",
  "frank ocean",
  "tyler, the creator",
  "tyler the creator",
  "childish gambino",
  "lil wayne",
  "eminem",
  "jay-z",
  "jay z",
  "kanye west",
  "ye",
  "future",
  "young thug",
  "gunna",
  "lil baby",
  "dababy",
  "roddy ricch",
  "polo g",
  "a boogie wit da hoodie",
  "a boogie",
  "meek mill",
  "21 savage",
  "playboi carti",
  "lil uzi vert",
  "yeat",
  "don toliver",
  "nav",
  "big sean",
  "logic",
  "joyner lucas",
  "nf",
  "machine gun kelly",
  "mgk",
  "g-eazy",
  "g eazy",
  "jack harlow",
  "ice spice",
  "latto",
  "megan thee stallion",
  "cardi b",
  "saweetie",
  "city girls",
  "flo milli",
  // 101-200
  "summer walker",
  "jhene aiko",
  "jhené aiko",
  "kehlani",
  "bryson tiller",
  "chris brown",
  "usher",
  "trey songz",
  "ne-yo",
  "alicia keys",
  "john legend",
  "mary j. blige",
  "mary j blige",
  "h.e.r.",
  "h.e.r",
  "daniel caesar",
  "giveon",
  "brent faiyaz",
  "partynextdoor",
  "ty dolla $ign",
  "ty dolla sign",
  "khalid",
  "zayn",
  "niall horan",
  "louis tomlinson",
  "liam payne",
  "jonas brothers",
  "nick jonas",
  "joe jonas",
  "dnce",
  "5 seconds of summer",
  "5sos",
  "the chainsmokers",
  "calvin harris",
  "david guetta",
  "avicii",
  "swedish house mafia",
  "tiësto",
  "tiesto",
  "martin garrix",
  "zedd",
  "kygo",
  "marshmello",
  "diplo",
  "major lazer",
  "skrillex",
  "porter robinson",
  "madeon",
  "illenium",
  "odesza",
  "deadmau5",
  "eric prydz",
  "armin van buuren",
  "hardwell",
  "alan walker",
  "purple disco machine",
  "fisher",
  "dom dolla",
  "peggy gou",
  "fred again",
  "fred again..",
  "disclosure",
  "jamie xx",
  "flume",
  "rufus du sol",
  "rüfüs du sol",
  "krewella",
  "ellie goulding",
  "charli xcx",
  "carly rae jepsen",
  "kim petras",
  "troye sivan",
  "tove lo",
  "robyn",
  "zara larsson",
  "anne-marie",
  "becky hill",
  "rita ora",
  "jessie j",
  "leona lewis",
  "natasha bedingfield",
  "dido",
  "sia",
  "p!nk",
  "pink",
  "kelly clarkson",
  "carrie underwood",
  "kelsea ballerini",
  "maren morris",
  "luke combs",
  "morgan wallen",
  "zach bryan",
  "chris stapleton",
  "blake shelton",
  "thomas rhett",
  "sam hunt",
  "kane brown",
  "dan + shay",
  "dan and shay",
  "florida georgia line",
  "jason aldean",
  "keith urban",
  "tim mcgraw",
  "faith hill",
  "shania twain",
  "dolly parton",
  "garth brooks",
  "rascal flatts",
  "brett young",
  "hardy",
  // 201-300
  "bts",
  "jungkook",
  "jung kook",
  "jimin",
  "v",
  "rm",
  "blackpink",
  "jennie",
  "lisa",
  "rosé",
  "rose",
  "stray kids",
  "txt",
  "seventeen",
  "enhypen",
  "ateez",
  "newjeans",
  "le sserafim",
  "ive",
  "aespa",
  "itzy",
  "twice",
  "red velvet",
  "nct 127",
  "nct dream",
  "superm",
  "exo",
  "baekhyun",
  "taemin",
  "bigbang",
  "big bang",
  "g-dragon",
  "g dragon",
  "taeyang",
  "psy",
  "iu",
  "jackson wang",
  "joji",
  "rich brian",
  "keshi",
  "niki",
  "jay park",
  "higher brothers",
  "badshah",
  "diljit dosanjh",
  "arijit singh",
  "sidhu moose wala",
  "wizkid",
  "burna boy",
  "tems",
  "davido",
  "rema",
  "ayra starr",
  "fireboy dml",
  "omah lay",
  "ckay",
  "tyla",
  "black coffee",
  "fally ipupa",
  "stromae",
  "angèle",
  "angele",
  "christine and the queens",
  "indila",
  "m83",
  "justice",
  "phoenix",
  "daft punk",
  "air",
  "the chemical brothers",
  "fatboy slim",
  "basement jaxx",
  "groove armada",
  "pet shop boys",
  "depeche mode",
  "new order",
  "the cure",
  "the smiths",
  "morrissey",
  "tears for fears",
  "duran duran",
  "a-ha",
  "george michael",
  "wham!",
  "wham",
  "elton john",
  "billy joel",
  "bruce springsteen",
  "bob dylan",
  "paul mccartney",
  "john lennon",
  "the beatles",
  "the rolling stones",
  "queen",
  "david bowie",
  "prince",
  "stevie wonder",
  "marvin gaye",
  "diana ross",
  "the supremes",
  "aretha franklin",
  "whitney houston",
  "celine dion",
  "céline dion",
  "barbra streisand",
  "cher",
  "tina turner",
  // 301-400
  "abba",
  "bee gees",
  "earth, wind & fire",
  "earth wind & fire",
  "chicago",
  "fleetwood mac",
  "eagles",
  "journey",
  "reo speedwagon",
  "toto",
  "def leppard",
  "bon jovi",
  "aerosmith",
  "guns n' roses",
  "guns n roses",
  "van halen",
  "kiss",
  "iron maiden",
  "slayer",
  "megadeth",
  "tool",
  "nine inch nails",
  "soundgarden",
  "alice in chains",
  "pearl jam",
  "nirvana",
  "smashing pumpkins",
  "beck",
  "weezer",
  "the strokes",
  "interpol",
  "yeah yeah yeahs",
  "vampire weekend",
  "mgmt",
  "foster the people",
  "glass animals",
  "ajr",
  "fun.",
  "bleachers",
  "jack antonoff",
  "børns",
  "borns",
  "bebe rexha",
  "ava max",
  "tate mcrae",
  "madison beer",
  "sabrina carpenter",
  "chappell roan",
  "gracie abrams",
  "conan gray",
  "alec benjamin",
  "lauv",
  "jeremy zucker",
  "alexander 23",
  "jvke",
  "stephen sanchez",
  "benson boone",
  "noah kahan",
  "dermot kennedy",
  "lewis capaldi",
  "tom grennan",
  "james bay",
  "vance joy",
  "passenger",
  "george ezra",
  "hozier",
  "mumford & sons",
  "mumford and sons",
  "the lumineers",
  "of monsters and men",
  "tyler childers",
  "sturgill simpson",
  "orville peck",
  "kacey musgraves",
  "brandi carlile",
  "norah jones",
  "diana krall",
  "michael bublé",
  "michael buble",
  "josh groban",
  "andrea bocelli",
  "il divo",
  "lang lang",
  "yo-yo ma",
  "lindsey stirling",
  "2cellos",
  "hans zimmer",
  "john williams",
  "howard shore",
  "danny elfman",
  "trent reznor",
  "atticus ross",
  "ludovico einaudi",
  "max richter",
  "ólafur arnalds",
  "olafur arnalds",
  "brian eno",
  "aphex twin",
  "autechre",
  "boards of canada",
  "four tet",
  "caribou",
  "nicolas jaar",
  "jon hopkins",
  "burial",
  "sophie",
  // 401-500
  "arca",
  "fka twigs",
  "kelela",
  "blood orange",
  "solange",
  "janelle monáe",
  "janelle monae",
  "erykah badu",
  "d'angelo",
  "dangelo",
  "maxwell",
  "raphael saadiq",
  "anderson .paak",
  "anderson paak",
  "silk sonic",
  "thundercat",
  "flying lotus",
  "kamasi washington",
  "robert glasper",
  "esperanza spalding",
  "snarky puppy",
  "jacob collier",
  "cory wong",
  "vulfpeck",
  "khruangbin",
  "jungle",
  "parcels",
  "chromeo",
  "empire of the sun",
  "cut copy",
  "hot chip",
  "metronomy",
  "little dragon",
  "santigold",
  "m.i.a.",
  "m.i.a",
  "azealia banks",
  "tinashe",
  "victoria monét",
  "victoria monet",
  "normani",
  "fifth harmony",
  "little mix",
  "girls aloud",
  "sugababes",
  "steps",
  "aqua",
  "eiffel 65",
  "haddaway",
  "corona",
  "la bouche",
  "ace of base",
  "real mccoy",
  "snap!",
  "technotronic",
  "jason derulo",
  "taio cruz",
  "iyaz",
  "sean kingston",
  "flo rida",
  "pitbull",
  "enrique iglesias",
  "ricky martin",
  "marc anthony",
  "maluma",
  "j balvin",
  "nicky jam",
  "farruko",
  "anuel aa",
  "ozuna",
  "wisin & yandel",
  "wisin y yandel",
  "don omar",
  "daddy yankee",
  "romeo santos",
  "prince royce",
  "aventura",
  "mon laferte",
  "kali uchis",
  "omar apollo",
  "steve aoki",
  "dillon francis",
  "rl grime",
  "yellow claw",
  "baauer",
  "cashmere cat",
  "alesso",
  "sebastian ingrosso",
  "steve angello",
  "axwell",
  "katseye",
  "sombr",
  "lola young",
  "pinkpantheress",
  "icewear vezzo",
  "central cee",
  "dave",
  "stormzy",
  "skepta",
  "aj tracey",
  "headie one",
  "pop smoke",
  "xxxtentacion",
  "juice wrld",
  "mac miller",
  "kid cudi",
  // Additional from prior filtering
  "ken carson",
  "lil yachty",
  "destroy lonely",
  "alex warren",
  "huncho",
  "quavo",
  "offset",
  "takeoff",
  "migos",
  "lil nas x",
  "lizzo",
  "fifty cent",
  "50 cent",
  "the kid laroi",
  "kid laroi",
  "one direction",
  "wiz khalifa",
  "snoop dogg",
  "dr. dre",
  "2pac",
  "tupac",
  "notorious b.i.g",
  "biggie",
  "nas",
  "j.i.d",
  "jid",
  "glorilla",
  "sexyy red",
  "asake",
  "metro boomin",
  "feid",
  "rauw alejandro",
  "myke towers",
  "lil durk",
  "rod wave",
  "nba youngboy",
  "youngboy never broke again",
  "moneybagg yo",
  "kodak black",
  "lil tecca",
  "asap rocky",
  "a$ap rocky",
];
